package com.mainconcept.rewsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-01-26T19:01:41.429+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "REWS", 
                  wsdlLocation = "http://192.168.1.167:8080/axis2/services/REWS?wsdl",
                  targetNamespace = "http://service.rews.mainconcept.com") 
public class REWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.rews.mainconcept.com", "REWS");
    public final static QName REWSHttpEndpoint = new QName("http://service.rews.mainconcept.com", "REWSHttpEndpoint");
    public final static QName REWSHttpSoap11Endpoint = new QName("http://service.rews.mainconcept.com", "REWSHttpSoap11Endpoint");
    public final static QName REWSHttpSoap12Endpoint = new QName("http://service.rews.mainconcept.com", "REWSHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.167:8080/axis2/services/REWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(REWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.167:8080/axis2/services/REWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public REWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public REWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public REWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public REWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public REWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public REWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpEndpoint")
    public REWSPortType getREWSHttpEndpoint() {
        return super.getPort(REWSHttpEndpoint, REWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpEndpoint")
    public REWSPortType getREWSHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(REWSHttpEndpoint, REWSPortType.class, features);
    }
    /**
     *
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpSoap11Endpoint")
    public REWSPortType getREWSHttpSoap11Endpoint() {
        return super.getPort(REWSHttpSoap11Endpoint, REWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpSoap11Endpoint")
    public REWSPortType getREWSHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(REWSHttpSoap11Endpoint, REWSPortType.class, features);
    }
    /**
     *
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpSoap12Endpoint")
    public REWSPortType getREWSHttpSoap12Endpoint() {
        return super.getPort(REWSHttpSoap12Endpoint, REWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns REWSPortType
     */
    @WebEndpoint(name = "REWSHttpSoap12Endpoint")
    public REWSPortType getREWSHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(REWSHttpSoap12Endpoint, REWSPortType.class, features);
    }

}
