package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpDownload generated by hbm2java
 */
public class DcpDownload implements java.io.Serializable {

	private Integer id;
	private DcpMedia dcpMedia;
	private Integer downloadCount;
	private Date createDate;
	private Date modifyDate;

	public DcpDownload() {
	}

	public DcpDownload(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public DcpDownload(DcpMedia dcpMedia, Integer downloadCount,
			Date createDate, Date modifyDate) {
		this.dcpMedia = dcpMedia;
		this.downloadCount = downloadCount;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DcpMedia getDcpMedia() {
		return this.dcpMedia;
	}

	public void setDcpMedia(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public Integer getDownloadCount() {
		return this.downloadCount;
	}

	public void setDownloadCount(Integer downloadCount) {
		this.downloadCount = downloadCount;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
