package com.divx.service.domain.model;

// Generated 2015-4-23 19:07:38 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpLesson generated by hbm2java
 */
public class DcpLesson implements java.io.Serializable {

	private Integer lessonId;
	private DcpMedia dcpMedia;
	private String category;
	private Integer number;
	private String title;
	private Date datecreated;
	private Date datemodified;
	private String snapshoturl;
	private Set dcpScores = new HashSet(0);

	public DcpLesson() {
	}

	public DcpLesson(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public DcpLesson(DcpMedia dcpMedia, String category, Integer number,
			String title, Date datecreated, Date datemodified,
			String snapshoturl, Set dcpScores) {
		this.dcpMedia = dcpMedia;
		this.category = category;
		this.number = number;
		this.title = title;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.snapshoturl = snapshoturl;
		this.dcpScores = dcpScores;
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public DcpMedia getDcpMedia() {
		return this.dcpMedia;
	}

	public void setDcpMedia(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public Set getDcpScores() {
		return this.dcpScores;
	}

	public void setDcpScores(Set dcpScores) {
		this.dcpScores = dcpScores;
	}

}
