package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpLogs generated by hbm2java
 */
public class DcpLogs implements java.io.Serializable {

	private Integer id;
	private String user;
	private Date datecreated;
	private String logger;
	private String level;
	private String message;

	public DcpLogs() {
	}

	public DcpLogs(Date datecreated, String logger, String level, String message) {
		this.datecreated = datecreated;
		this.logger = logger;
		this.level = level;
		this.message = message;
	}

	public DcpLogs(String user, Date datecreated, String logger, String level,
			String message) {
		this.user = user;
		this.datecreated = datecreated;
		this.logger = logger;
		this.level = level;
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public String getLogger() {
		return this.logger;
	}

	public void setLogger(String logger) {
		this.logger = logger;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
