package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpLessonAsset generated by hbm2java
 */
public class DcpLessonAsset implements java.io.Serializable {

	private Integer lessonassetId;
	private DcpLesson dcpLesson;
	private int assettype;
	private String content;
	private Date datecreated;
	private Date datemodified;

	public DcpLessonAsset() {
	}

	public DcpLessonAsset(DcpLesson dcpLesson, int assettype, Date datecreated,
			Date datemodified) {
		this.dcpLesson = dcpLesson;
		this.assettype = assettype;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public DcpLessonAsset(DcpLesson dcpLesson, int assettype, String content,
			Date datecreated, Date datemodified) {
		this.dcpLesson = dcpLesson;
		this.assettype = assettype;
		this.content = content;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public Integer getLessonassetId() {
		return this.lessonassetId;
	}

	public void setLessonassetId(Integer lessonassetId) {
		this.lessonassetId = lessonassetId;
	}

	public DcpLesson getDcpLesson() {
		return this.dcpLesson;
	}

	public void setDcpLesson(DcpLesson dcpLesson) {
		this.dcpLesson = dcpLesson;
	}

	public int getAssettype() {
		return this.assettype;
	}

	public void setAssettype(int assettype) {
		this.assettype = assettype;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

}
