package com.divx.service.domain.model;

// Generated 2015-6-10 13:52:48 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpLesson generated by hbm2java
 */
public class DcpLesson implements java.io.Serializable {

	private Integer lessonId;
	private DcpMedia dcpMedia;
	private String category;
	private String categoryTitle;
	private Integer number;
	private String title;
	private String config;
	private Date datecreated;
	private Date datemodified;
	private String snapshoturl;
	private Set dcpStoryplayTotalstats = new HashSet(0);
	private Set dcpStoryplays = new HashSet(0);
	private Set dcpLessonAssets = new HashSet(0);
	private Set dcpScores = new HashSet(0);

	public DcpLesson() {
	}

	public DcpLesson(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public DcpLesson(DcpMedia dcpMedia, String category, String categoryTitle,
			Integer number, String title, String config, Date datecreated,
			Date datemodified, String snapshoturl, Set dcpStoryplayTotalstats,
			Set dcpStoryplays, Set dcpLessonAssets, Set dcpScores) {
		this.dcpMedia = dcpMedia;
		this.category = category;
		this.categoryTitle = categoryTitle;
		this.number = number;
		this.title = title;
		this.config = config;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.snapshoturl = snapshoturl;
		this.dcpStoryplayTotalstats = dcpStoryplayTotalstats;
		this.dcpStoryplays = dcpStoryplays;
		this.dcpLessonAssets = dcpLessonAssets;
		this.dcpScores = dcpScores;
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public DcpMedia getDcpMedia() {
		return this.dcpMedia;
	}

	public void setDcpMedia(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getCategoryTitle() {
		return this.categoryTitle;
	}

	public void setCategoryTitle(String categoryTitle) {
		this.categoryTitle = categoryTitle;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getConfig() {
		return this.config;
	}

	public void setConfig(String config) {
		this.config = config;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public Set getDcpStoryplayTotalstats() {
		return this.dcpStoryplayTotalstats;
	}

	public void setDcpStoryplayTotalstats(Set dcpStoryplayTotalstats) {
		this.dcpStoryplayTotalstats = dcpStoryplayTotalstats;
	}

	public Set getDcpStoryplays() {
		return this.dcpStoryplays;
	}

	public void setDcpStoryplays(Set dcpStoryplays) {
		this.dcpStoryplays = dcpStoryplays;
	}

	public Set getDcpLessonAssets() {
		return this.dcpLessonAssets;
	}

	public void setDcpLessonAssets(Set dcpLessonAssets) {
		this.dcpLessonAssets = dcpLessonAssets;
	}

	public Set getDcpScores() {
		return this.dcpScores;
	}

	public void setDcpScores(Set dcpScores) {
		this.dcpScores = dcpScores;
	}

}
