package com.divx.service.domain.model;

// Generated 2015-4-23 19:07:38 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpMedia generated by hbm2java
 */
public class DcpMedia implements java.io.Serializable {

	private Integer mediaId;
	private String title;
	private Date datecreated;
	private Date datemodified;
	private int userId;
	private int status;
	private Date expiredate;
	private String description;
	private boolean deleted;
	private String snapshoturl;
	private String errorlog;
	private Integer contenttype;
	private Integer parentId;
	private Set dcpLessons = new HashSet(0);

	public DcpMedia() {
	}

	public DcpMedia(String title, Date datecreated, Date datemodified,
			int userId, int status, Date expiredate, String description,
			boolean deleted) {
		this.title = title;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.userId = userId;
		this.status = status;
		this.expiredate = expiredate;
		this.description = description;
		this.deleted = deleted;
	}

	public DcpMedia(String title, Date datecreated, Date datemodified,
			int userId, int status, Date expiredate, String description,
			boolean deleted, String snapshoturl, String errorlog,
			Integer contenttype, Integer parentId, Set dcpLessons) {
		this.title = title;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.userId = userId;
		this.status = status;
		this.expiredate = expiredate;
		this.description = description;
		this.deleted = deleted;
		this.snapshoturl = snapshoturl;
		this.errorlog = errorlog;
		this.contenttype = contenttype;
		this.parentId = parentId;
		this.dcpLessons = dcpLessons;
	}

	public Integer getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public String getErrorlog() {
		return this.errorlog;
	}

	public void setErrorlog(String errorlog) {
		this.errorlog = errorlog;
	}

	public Integer getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(Integer contenttype) {
		this.contenttype = contenttype;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Set getDcpLessons() {
		return this.dcpLessons;
	}

	public void setDcpLessons(Set dcpLessons) {
		this.dcpLessons = dcpLessons;
	}

}
