package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpMedia generated by hbm2java
 */
public class DcpMedia implements java.io.Serializable {

	private Integer mediaId;
	private String title;
	private Date datecreated;
	private Date datemodified;
	private int userId;
	private int status;
	private Date expiredate;
	private String description;
	private boolean deleted;
	private String snapshoturl;
	private String errorlog;
	private Integer contenttype;
	private Integer parentId;
	private Boolean ispublic;
	private String contentSettings;
	private Integer weight;
	private Integer lessonId;
	private Integer appversion;
	private Integer transferUserId;
	private Set dcpStoryplayTotalstats = new HashSet(0);
	private Set dcpLessons = new HashSet(0);
	private Set dcpMediaSigns = new HashSet(0);
	private Set dcpDownloads = new HashSet(0);
	private Set dcpStoryplays = new HashSet(0);

	public DcpMedia() {
	}

	public DcpMedia(String title, Date datecreated, Date datemodified,
			int userId, int status, Date expiredate, String description,
			boolean deleted) {
		this.title = title;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.userId = userId;
		this.status = status;
		this.expiredate = expiredate;
		this.description = description;
		this.deleted = deleted;
	}

	public DcpMedia(String title, Date datecreated, Date datemodified,
			int userId, int status, Date expiredate, String description,
			boolean deleted, String snapshoturl, String errorlog,
			Integer contenttype, Integer parentId, Boolean ispublic,
			String contentSettings, Integer weight, Integer lessonId,
			Integer appversion, Integer transferUserId,
			Set dcpStoryplayTotalstats, Set dcpLessons, Set dcpMediaSigns,
			Set dcpDownloads, Set dcpStoryplays) {
		this.title = title;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.userId = userId;
		this.status = status;
		this.expiredate = expiredate;
		this.description = description;
		this.deleted = deleted;
		this.snapshoturl = snapshoturl;
		this.errorlog = errorlog;
		this.contenttype = contenttype;
		this.parentId = parentId;
		this.ispublic = ispublic;
		this.contentSettings = contentSettings;
		this.weight = weight;
		this.lessonId = lessonId;
		this.appversion = appversion;
		this.transferUserId = transferUserId;
		this.dcpStoryplayTotalstats = dcpStoryplayTotalstats;
		this.dcpLessons = dcpLessons;
		this.dcpMediaSigns = dcpMediaSigns;
		this.dcpDownloads = dcpDownloads;
		this.dcpStoryplays = dcpStoryplays;
	}

	public Integer getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public String getErrorlog() {
		return this.errorlog;
	}

	public void setErrorlog(String errorlog) {
		this.errorlog = errorlog;
	}

	public Integer getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(Integer contenttype) {
		this.contenttype = contenttype;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Boolean getIspublic() {
		return this.ispublic;
	}

	public void setIspublic(Boolean ispublic) {
		this.ispublic = ispublic;
	}

	public String getContentSettings() {
		return this.contentSettings;
	}

	public void setContentSettings(String contentSettings) {
		this.contentSettings = contentSettings;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public Integer getAppversion() {
		return this.appversion;
	}

	public void setAppversion(Integer appversion) {
		this.appversion = appversion;
	}

	public Integer getTransferUserId() {
		return this.transferUserId;
	}

	public void setTransferUserId(Integer transferUserId) {
		this.transferUserId = transferUserId;
	}

	public Set getDcpStoryplayTotalstats() {
		return this.dcpStoryplayTotalstats;
	}

	public void setDcpStoryplayTotalstats(Set dcpStoryplayTotalstats) {
		this.dcpStoryplayTotalstats = dcpStoryplayTotalstats;
	}

	public Set getDcpLessons() {
		return this.dcpLessons;
	}

	public void setDcpLessons(Set dcpLessons) {
		this.dcpLessons = dcpLessons;
	}

	public Set getDcpMediaSigns() {
		return this.dcpMediaSigns;
	}

	public void setDcpMediaSigns(Set dcpMediaSigns) {
		this.dcpMediaSigns = dcpMediaSigns;
	}

	public Set getDcpDownloads() {
		return this.dcpDownloads;
	}

	public void setDcpDownloads(Set dcpDownloads) {
		this.dcpDownloads = dcpDownloads;
	}

	public Set getDcpStoryplays() {
		return this.dcpStoryplays;
	}

	public void setDcpStoryplays(Set dcpStoryplays) {
		this.dcpStoryplays = dcpStoryplays;
	}

}
