package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpMediaSign generated by hbm2java
 */
public class DcpMediaSign implements java.io.Serializable {

	private Integer id;
	private DcpMedia dcpMedia;
	private String sign;
	private Date createDate;
	private Date modifyDate;

	public DcpMediaSign() {
	}

	public DcpMediaSign(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public DcpMediaSign(DcpMedia dcpMedia, String sign, Date createDate,
			Date modifyDate) {
		this.dcpMedia = dcpMedia;
		this.sign = sign;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DcpMedia getDcpMedia() {
		return this.dcpMedia;
	}

	public void setDcpMedia(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
