package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpOriginalasset generated by hbm2java
 */
public class DcpOriginalasset implements java.io.Serializable {

	private Integer id;
	private int originalassetId;
	private int mediaId;
	private String fileurl;
	private Date datecreated;
	private Date datemodified;
	private boolean deleted;

	public DcpOriginalasset() {
	}

	public DcpOriginalasset(int originalassetId, int mediaId, String fileurl,
			Date datecreated, Date datemodified, boolean deleted) {
		this.originalassetId = originalassetId;
		this.mediaId = mediaId;
		this.fileurl = fileurl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.deleted = deleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOriginalassetId() {
		return this.originalassetId;
	}

	public void setOriginalassetId(int originalassetId) {
		this.originalassetId = originalassetId;
	}

	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	public String getFileurl() {
		return this.fileurl;
	}

	public void setFileurl(String fileurl) {
		this.fileurl = fileurl;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

}
