package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpStoryplay generated by hbm2java
 */
public class DcpStoryplay implements java.io.Serializable {

	private Integer id;
	private DcpLesson dcpLesson;
	private DcpMedia dcpMedia;
	private Date datecreated;

	public DcpStoryplay() {
	}

	public DcpStoryplay(DcpLesson dcpLesson, DcpMedia dcpMedia, Date datecreated) {
		this.dcpLesson = dcpLesson;
		this.dcpMedia = dcpMedia;
		this.datecreated = datecreated;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DcpLesson getDcpLesson() {
		return this.dcpLesson;
	}

	public void setDcpLesson(DcpLesson dcpLesson) {
		this.dcpLesson = dcpLesson;
	}

	public DcpMedia getDcpMedia() {
		return this.dcpMedia;
	}

	public void setDcpMedia(DcpMedia dcpMedia) {
		this.dcpMedia = dcpMedia;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

}
