package com.divx.service.domain.model;

// Generated 2015-6-9 11:04:13 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpScorestat generated by hbm2java
 */
public class DcpScorestat implements java.io.Serializable {

	private Integer statId;
	private DcpScore dcpScore;
	private int userId;
	private Date datecreated;
	private Integer listenduration;
	private Integer readduration;
	private Integer recordduration;
	private Integer readcount;
	private Integer stattype;

	public DcpScorestat() {
	}

	public DcpScorestat(DcpScore dcpScore, int userId) {
		this.dcpScore = dcpScore;
		this.userId = userId;
	}

	public DcpScorestat(DcpScore dcpScore, int userId, Date datecreated,
			Integer listenduration, Integer readduration,
			Integer recordduration, Integer readcount, Integer stattype) {
		this.dcpScore = dcpScore;
		this.userId = userId;
		this.datecreated = datecreated;
		this.listenduration = listenduration;
		this.readduration = readduration;
		this.recordduration = recordduration;
		this.readcount = readcount;
		this.stattype = stattype;
	}

	public Integer getStatId() {
		return this.statId;
	}

	public void setStatId(Integer statId) {
		this.statId = statId;
	}

	public DcpScore getDcpScore() {
		return this.dcpScore;
	}

	public void setDcpScore(DcpScore dcpScore) {
		this.dcpScore = dcpScore;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Integer getListenduration() {
		return this.listenduration;
	}

	public void setListenduration(Integer listenduration) {
		this.listenduration = listenduration;
	}

	public Integer getReadduration() {
		return this.readduration;
	}

	public void setReadduration(Integer readduration) {
		this.readduration = readduration;
	}

	public Integer getRecordduration() {
		return this.recordduration;
	}

	public void setRecordduration(Integer recordduration) {
		this.recordduration = recordduration;
	}

	public Integer getReadcount() {
		return this.readcount;
	}

	public void setReadcount(Integer readcount) {
		this.readcount = readcount;
	}

	public Integer getStattype() {
		return this.stattype;
	}

	public void setStattype(Integer stattype) {
		this.stattype = stattype;
	}

}
