package com.divx.service.domain.model;

// Generated 2015-4-23 19:07:38 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpScore generated by hbm2java
 */
public class DcpScore implements java.io.Serializable {

	private Integer scoreId;
	private DcpLesson dcpLesson;
	private Integer listen;
	private Integer read;
	private Integer record;
	private Integer score;
	private Date datecreated;
	private Date datemodified;
	private Integer listenduration;
	private Integer readduration;
	private Integer recordduration;

	public DcpScore() {
	}

	public DcpScore(DcpLesson dcpLesson) {
		this.dcpLesson = dcpLesson;
	}

	public DcpScore(DcpLesson dcpLesson, Integer listen, Integer read,
			Integer record, Integer score, Date datecreated, Date datemodified,
			Integer listenduration, Integer readduration, Integer recordduration) {
		this.dcpLesson = dcpLesson;
		this.listen = listen;
		this.read = read;
		this.record = record;
		this.score = score;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.listenduration = listenduration;
		this.readduration = readduration;
		this.recordduration = recordduration;
	}

	public Integer getScoreId() {
		return this.scoreId;
	}

	public void setScoreId(Integer scoreId) {
		this.scoreId = scoreId;
	}

	public DcpLesson getDcpLesson() {
		return this.dcpLesson;
	}

	public void setDcpLesson(DcpLesson dcpLesson) {
		this.dcpLesson = dcpLesson;
	}

	public Integer getListen() {
		return this.listen;
	}

	public void setListen(Integer listen) {
		this.listen = listen;
	}

	public Integer getRead() {
		return this.read;
	}

	public void setRead(Integer read) {
		this.read = read;
	}

	public Integer getRecord() {
		return this.record;
	}

	public void setRecord(Integer record) {
		this.record = record;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Integer getListenduration() {
		return this.listenduration;
	}

	public void setListenduration(Integer listenduration) {
		this.listenduration = listenduration;
	}

	public Integer getReadduration() {
		return this.readduration;
	}

	public void setReadduration(Integer readduration) {
		this.readduration = readduration;
	}

	public Integer getRecordduration() {
		return this.recordduration;
	}

	public void setRecordduration(Integer recordduration) {
		this.recordduration = recordduration;
	}

}
