package com.divx.service.domain.model;

// Generated 2015-6-1 16:15:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpTotalstat generated by hbm2java
 */
public class DcpTotalstat implements java.io.Serializable {

	private Integer totalstatId;
	private int userId;
	private Integer listen;
	private Integer read;
	private Integer record;
	private Integer score;
	private Integer listenduration;
	private Integer readduration;
	private Integer recordduration;
	private Date datemodified;
	private Date datecreated;

	public DcpTotalstat() {
	}

	public DcpTotalstat(int userId) {
		this.userId = userId;
	}

	public DcpTotalstat(int userId, Integer listen, Integer read,
			Integer record, Integer score, Integer listenduration,
			Integer readduration, Integer recordduration, Date datemodified,
			Date datecreated) {
		this.userId = userId;
		this.listen = listen;
		this.read = read;
		this.record = record;
		this.score = score;
		this.listenduration = listenduration;
		this.readduration = readduration;
		this.recordduration = recordduration;
		this.datemodified = datemodified;
		this.datecreated = datecreated;
	}

	public Integer getTotalstatId() {
		return this.totalstatId;
	}

	public void setTotalstatId(Integer totalstatId) {
		this.totalstatId = totalstatId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Integer getListen() {
		return this.listen;
	}

	public void setListen(Integer listen) {
		this.listen = listen;
	}

	public Integer getRead() {
		return this.read;
	}

	public void setRead(Integer read) {
		this.read = read;
	}

	public Integer getRecord() {
		return this.record;
	}

	public void setRecord(Integer record) {
		this.record = record;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getListenduration() {
		return this.listenduration;
	}

	public void setListenduration(Integer listenduration) {
		this.listenduration = listenduration;
	}

	public Integer getReadduration() {
		return this.readduration;
	}

	public void setReadduration(Integer readduration) {
		this.readduration = readduration;
	}

	public Integer getRecordduration() {
		return this.recordduration;
	}

	public void setRecordduration(Integer recordduration) {
		this.recordduration = recordduration;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

}
