
package com.divx.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Mon Sep 15 14:53:44 CST 2014
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "MyFriendRequests", namespace = "http://service.divx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MyFriendRequests", namespace = "http://service.divx.com/")

public class MyFriendRequests {


}

