
package org.androidpn.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Mon Dec 29 16:42:37 CST 2014
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "sendNotificationResponse", namespace = "http://service.androidpn.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendNotificationResponse", namespace = "http://service.androidpn.org/")

public class SendNotificationResponse {

    @XmlElement(name = "return")
    private javax.ws.rs.core.Response _return;

    public javax.ws.rs.core.Response getReturn() {
        return this._return;
    }

    public void setReturn(javax.ws.rs.core.Response new_return)  {
        this._return = new_return;
    }

}

