package com.divx.service.domain.model;

// Generated 2015-4-14 17:45:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpEmailJob generated by hbm2java
 */
public class DcpEmailJob implements java.io.Serializable {

	private Integer id;
	private boolean status;
	private Date createdate;
	private Date modifydate;
	private int userId;
	private String emailAddress;
	private String content;
	private int attempts;
	private int emailType;

	public DcpEmailJob() {
	}

	public DcpEmailJob(boolean status, int userId, String emailAddress,
			int attempts, int emailType) {
		this.status = status;
		this.userId = userId;
		this.emailAddress = emailAddress;
		this.attempts = attempts;
		this.emailType = emailType;
	}

	public DcpEmailJob(boolean status, Date createdate, Date modifydate,
			int userId, String emailAddress, String content, int attempts,
			int emailType) {
		this.status = status;
		this.createdate = createdate;
		this.modifydate = modifydate;
		this.userId = userId;
		this.emailAddress = emailAddress;
		this.content = content;
		this.attempts = attempts;
		this.emailType = emailType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getAttempts() {
		return this.attempts;
	}

	public void setAttempts(int attempts) {
		this.attempts = attempts;
	}

	public int getEmailType() {
		return this.emailType;
	}

	public void setEmailType(int emailType) {
		this.emailType = emailType;
	}

}
