package com.divx.service.domain.model;

// Generated 2015-6-11 16:01:06 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpImSync generated by hbm2java
 */
public class DcpImSync implements java.io.Serializable {

	private int id;
	private OsfUsers osfUsers;
	private boolean synced;
	private Date datecreated;
	private Date datemodified;
	private Integer syncType;
	private Integer tryCount;
	private String errorMessage;

	public DcpImSync() {
	}

	public DcpImSync(int id, OsfUsers osfUsers, boolean synced) {
		this.id = id;
		this.osfUsers = osfUsers;
		this.synced = synced;
	}

	public DcpImSync(int id, OsfUsers osfUsers, boolean synced,
			Date datecreated, Date datemodified, Integer syncType,
			Integer tryCount, String errorMessage) {
		this.id = id;
		this.osfUsers = osfUsers;
		this.synced = synced;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.syncType = syncType;
		this.tryCount = tryCount;
		this.errorMessage = errorMessage;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public OsfUsers getOsfUsers() {
		return this.osfUsers;
	}

	public void setOsfUsers(OsfUsers osfUsers) {
		this.osfUsers = osfUsers;
	}

	public boolean isSynced() {
		return this.synced;
	}

	public void setSynced(boolean synced) {
		this.synced = synced;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Integer getSyncType() {
		return this.syncType;
	}

	public void setSyncType(Integer syncType) {
		this.syncType = syncType;
	}

	public Integer getTryCount() {
		return this.tryCount;
	}

	public void setTryCount(Integer tryCount) {
		this.tryCount = tryCount;
	}

	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

}
