package com.divx.service.domain.model;

// Generated 2015-2-6 15:30:04 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpOrganization generated by hbm2java
 */
public class DcpOrganization implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private String homeurl;
	private Date datecreated;
	private Date datemodified;
	private Set dcpOrgsites = new HashSet(0);

	public DcpOrganization() {
	}

	public DcpOrganization(String title, String homeurl, Date datecreated,
			Date datemodified) {
		this.title = title;
		this.homeurl = homeurl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public DcpOrganization(String title, String description, String homeurl,
			Date datecreated, Date datemodified, Set dcpOrgsites) {
		this.title = title;
		this.description = description;
		this.homeurl = homeurl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.dcpOrgsites = dcpOrgsites;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getHomeurl() {
		return this.homeurl;
	}

	public void setHomeurl(String homeurl) {
		this.homeurl = homeurl;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Set getDcpOrgsites() {
		return this.dcpOrgsites;
	}

	public void setDcpOrgsites(Set dcpOrgsites) {
		this.dcpOrgsites = dcpOrgsites;
	}

}
