package com.divx.service.domain.model;

// Generated 2015-2-6 15:30:04 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpOrgsite generated by hbm2java
 */
public class DcpOrgsite implements java.io.Serializable {

	private Integer id;
	private DcpOrganization dcpOrganization;
	private int siteId;
	private String sitename;
	private String siteurl;
	private Date datecreated;
	private Date datemodified;

	public DcpOrgsite() {
	}

	public DcpOrgsite(DcpOrganization dcpOrganization, int siteId,
			String sitename, String siteurl, Date datecreated, Date datemodified) {
		this.dcpOrganization = dcpOrganization;
		this.siteId = siteId;
		this.sitename = sitename;
		this.siteurl = siteurl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DcpOrganization getDcpOrganization() {
		return this.dcpOrganization;
	}

	public void setDcpOrganization(DcpOrganization dcpOrganization) {
		this.dcpOrganization = dcpOrganization;
	}

	public int getSiteId() {
		return this.siteId;
	}

	public void setSiteId(int siteId) {
		this.siteId = siteId;
	}

	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getSiteurl() {
		return this.siteurl;
	}

	public void setSiteurl(String siteurl) {
		this.siteurl = siteurl;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

}
