package com.divx.service.domain.model;

// Generated 2015-4-22 18:48:52 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpOauthUsers generated by hbm2java
 */
public class DcpOauthUsers implements java.io.Serializable {

	private Integer id;
	private OsfUsers osfUsers;
	private String accessToken;
	private String openId;
	private int oauthType;
	private Date createDate;
	private Date modifyDate;

	public DcpOauthUsers() {
	}

	public DcpOauthUsers(OsfUsers osfUsers, String accessToken, String openId,
			int oauthType) {
		this.osfUsers = osfUsers;
		this.accessToken = accessToken;
		this.openId = openId;
		this.oauthType = oauthType;
	}

	public DcpOauthUsers(OsfUsers osfUsers, String accessToken, String openId,
			int oauthType, Date createDate, Date modifyDate) {
		this.osfUsers = osfUsers;
		this.accessToken = accessToken;
		this.openId = openId;
		this.oauthType = oauthType;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public OsfUsers getOsfUsers() {
		return this.osfUsers;
	}

	public void setOsfUsers(OsfUsers osfUsers) {
		this.osfUsers = osfUsers;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public int getOauthType() {
		return this.oauthType;
	}

	public void setOauthType(int oauthType) {
		this.oauthType = oauthType;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
