package com.divx.service.domain.model;

// Generated 2015-6-11 16:01:06 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpUserExt generated by hbm2java
 */
public class DcpUserExt implements java.io.Serializable {

	private int userId;
	private String realname;
	private Integer gender;
	private Date birthday;
	private String selfintroduce;
	private String comefrom;
	private String im;
	private String im2;
	private String mobile2;
	private String email2;
	private String telephone;
	private String tdcImg;
	private Date datecreated;
	private Date datemodified;
	private String signature;
	private String homepage;

	public DcpUserExt() {
	}

	public DcpUserExt(int userId, Date datecreated, Date datemodified) {
		this.userId = userId;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public DcpUserExt(int userId, String realname, Integer gender,
			Date birthday, String selfintroduce, String comefrom, String im,
			String im2, String mobile2, String email2, String telephone,
			String tdcImg, Date datecreated, Date datemodified,
			String signature, String homepage) {
		this.userId = userId;
		this.realname = realname;
		this.gender = gender;
		this.birthday = birthday;
		this.selfintroduce = selfintroduce;
		this.comefrom = comefrom;
		this.im = im;
		this.im2 = im2;
		this.mobile2 = mobile2;
		this.email2 = email2;
		this.telephone = telephone;
		this.tdcImg = tdcImg;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.signature = signature;
		this.homepage = homepage;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSelfintroduce() {
		return this.selfintroduce;
	}

	public void setSelfintroduce(String selfintroduce) {
		this.selfintroduce = selfintroduce;
	}

	public String getComefrom() {
		return this.comefrom;
	}

	public void setComefrom(String comefrom) {
		this.comefrom = comefrom;
	}

	public String getIm() {
		return this.im;
	}

	public void setIm(String im) {
		this.im = im;
	}

	public String getIm2() {
		return this.im2;
	}

	public void setIm2(String im2) {
		this.im2 = im2;
	}

	public String getMobile2() {
		return this.mobile2;
	}

	public void setMobile2(String mobile2) {
		this.mobile2 = mobile2;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getTdcImg() {
		return this.tdcImg;
	}

	public void setTdcImg(String tdcImg) {
		this.tdcImg = tdcImg;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

}
