package com.divx.service.domain.model;

// Generated 2015-4-22 18:48:52 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OsfUsers generated by hbm2java
 */
public class OsfUsers implements java.io.Serializable {

	private Long id;
	private String email;
	private boolean enabled;
	private Date entered;
	private Date lastLogin;
	private String locale;
	private String nickname;
	private String password;
	private String timezone;
	private String token;
	private String username;
	private Long projectId;
	private String mobile;
	private Integer usernametype;
	private String photourl;
	private Integer organizationId;
	private Set dcpOauthUserses = new HashSet(0);
	private Set dcpUserRoles = new HashSet(0);

	public OsfUsers() {
	}

	public OsfUsers(String email, boolean enabled, Date entered,
			String nickname, String password, String username) {
		this.email = email;
		this.enabled = enabled;
		this.entered = entered;
		this.nickname = nickname;
		this.password = password;
		this.username = username;
	}

	public OsfUsers(String email, boolean enabled, Date entered,
			Date lastLogin, String locale, String nickname, String password,
			String timezone, String token, String username, Long projectId,
			String mobile, Integer usernametype, String photourl,
			Integer organizationId, Set dcpOauthUserses, Set dcpUserRoles) {
		this.email = email;
		this.enabled = enabled;
		this.entered = entered;
		this.lastLogin = lastLogin;
		this.locale = locale;
		this.nickname = nickname;
		this.password = password;
		this.timezone = timezone;
		this.token = token;
		this.username = username;
		this.projectId = projectId;
		this.mobile = mobile;
		this.usernametype = usernametype;
		this.photourl = photourl;
		this.organizationId = organizationId;
		this.dcpOauthUserses = dcpOauthUserses;
		this.dcpUserRoles = dcpUserRoles;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Integer getUsernametype() {
		return this.usernametype;
	}

	public void setUsernametype(Integer usernametype) {
		this.usernametype = usernametype;
	}

	public String getPhotourl() {
		return this.photourl;
	}

	public void setPhotourl(String photourl) {
		this.photourl = photourl;
	}

	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	public Set getDcpOauthUserses() {
		return this.dcpOauthUserses;
	}

	public void setDcpOauthUserses(Set dcpOauthUserses) {
		this.dcpOauthUserses = dcpOauthUserses;
	}

	public Set getDcpUserRoles() {
		return this.dcpUserRoles;
	}

	public void setDcpUserRoles(Set dcpUserRoles) {
		this.dcpUserRoles = dcpUserRoles;
	}

}
