<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="storage" targetNamespace="http://service.divx.com/" xmlns:ns1="http://service.divx.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.divx.com/" schemaLocation="storage_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="GetUploadInfo">
    <wsdl:part name="parameters" element="ns1:GetUploadInfo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetUploadInfoResponse">
    <wsdl:part name="parameters" element="ns1:GetUploadInfoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="storage">
    <wsdl:operation name="GetUploadInfo">
      <wsdl:input name="GetUploadInfo" message="ns1:GetUploadInfo">
    </wsdl:input>
      <wsdl:output name="GetUploadInfoResponse" message="ns1:GetUploadInfoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
