
package com.divx.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Thu Sep 18 14:47:29 CST 2014
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "LoginResponse", namespace = "http://service.divx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginResponse", namespace = "http://service.divx.com/")

public class LoginResponse {

    @XmlElement(name = "return")
    private com.divx.service.model.AuthResponse _return;

    public com.divx.service.model.AuthResponse getReturn() {
        return this._return;
    }

    public void setReturn(com.divx.service.model.AuthResponse new_return)  {
        this._return = new_return;
    }

}

