package com.divx.service.domain.model;

// Generated 2014-11-14 13:24:51 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpConfig generated by hbm2java
 */
public class DcpConfig implements java.io.Serializable {

	private Integer id;
	private String key;
	private String value;
	private String description;
	private Date datecreate;
	private Date datemodify;
	private Integer userId;

	public DcpConfig() {
	}

	public DcpConfig(String key, String value, Date datecreate, Date datemodify) {
		this.key = key;
		this.value = value;
		this.datecreate = datecreate;
		this.datemodify = datemodify;
	}

	public DcpConfig(String key, String value, String description,
			Date datecreate, Date datemodify, Integer userId) {
		this.key = key;
		this.value = value;
		this.description = description;
		this.datecreate = datecreate;
		this.datemodify = datemodify;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}

	public Date getDatemodify() {
		return this.datemodify;
	}

	public void setDatemodify(Date datemodify) {
		this.datemodify = datemodify;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
