package com.divx.service.domain.model;

// Generated 2014-12-30 10:29:19 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpMessageRecver generated by hbm2java
 */
public class DcpMessageRecver implements java.io.Serializable {

	private Integer messageRecverId;
	private Integer status;
	private Date datecreated;
	private int messageId;
	private int userId;
	private int iosStatus;
	private int iosAttemps;
	private int androidStatus;
	private int androidAttemps;

	public DcpMessageRecver() {
	}

	public DcpMessageRecver(Date datecreated, int messageId, int userId,
			int iosStatus, int iosAttemps, int androidStatus, int androidAttemps) {
		this.datecreated = datecreated;
		this.messageId = messageId;
		this.userId = userId;
		this.iosStatus = iosStatus;
		this.iosAttemps = iosAttemps;
		this.androidStatus = androidStatus;
		this.androidAttemps = androidAttemps;
	}

	public DcpMessageRecver(Integer status, Date datecreated, int messageId,
			int userId, int iosStatus, int iosAttemps, int androidStatus,
			int androidAttemps) {
		this.status = status;
		this.datecreated = datecreated;
		this.messageId = messageId;
		this.userId = userId;
		this.iosStatus = iosStatus;
		this.iosAttemps = iosAttemps;
		this.androidStatus = androidStatus;
		this.androidAttemps = androidAttemps;
	}

	public Integer getMessageRecverId() {
		return this.messageRecverId;
	}

	public void setMessageRecverId(Integer messageRecverId) {
		this.messageRecverId = messageRecverId;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getIosStatus() {
		return this.iosStatus;
	}

	public void setIosStatus(int iosStatus) {
		this.iosStatus = iosStatus;
	}

	public int getIosAttemps() {
		return this.iosAttemps;
	}

	public void setIosAttemps(int iosAttemps) {
		this.iosAttemps = iosAttemps;
	}

	public int getAndroidStatus() {
		return this.androidStatus;
	}

	public void setAndroidStatus(int androidStatus) {
		this.androidStatus = androidStatus;
	}

	public int getAndroidAttemps() {
		return this.androidAttemps;
	}

	public void setAndroidAttemps(int androidAttemps) {
		this.androidAttemps = androidAttemps;
	}

}
