package com.divx.service.domain.model;

// Generated 2014-11-3 18:28:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpRecver generated by hbm2java
 */
public class DcpRecver implements java.io.Serializable {

	private int userId;
	private String username;
	private String nickname;
	private Date datecreated;
	private boolean isactive;
	private String photourl;

	public DcpRecver() {
	}

	public DcpRecver(int userId, Date datecreated, boolean isactive) {
		this.userId = userId;
		this.datecreated = datecreated;
		this.isactive = isactive;
	}

	public DcpRecver(int userId, String username, String nickname,
			Date datecreated, boolean isactive, String photourl) {
		this.userId = userId;
		this.username = username;
		this.nickname = nickname;
		this.datecreated = datecreated;
		this.isactive = isactive;
		this.photourl = photourl;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public boolean isIsactive() {
		return this.isactive;
	}

	public void setIsactive(boolean isactive) {
		this.isactive = isactive;
	}

	public String getPhotourl() {
		return this.photourl;
	}

	public void setPhotourl(String photourl) {
		this.photourl = photourl;
	}

}
