package com.divx.service.domain.model;

// Generated 2014-11-3 18:28:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpSender generated by hbm2java
 */
public class DcpSender implements java.io.Serializable {

	private Integer senderId;
	private int type;
	private String nickname;
	private Date datecreated;
	private Integer linkId;
	private String description;

	public DcpSender() {
	}

	public DcpSender(int type, Date datecreated) {
		this.type = type;
		this.datecreated = datecreated;
	}

	public DcpSender(int type, String nickname, Date datecreated,
			Integer linkId, String description) {
		this.type = type;
		this.nickname = nickname;
		this.datecreated = datecreated;
		this.linkId = linkId;
		this.description = description;
	}

	public Integer getSenderId() {
		return this.senderId;
	}

	public void setSenderId(Integer senderId) {
		this.senderId = senderId;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Integer getLinkId() {
		return this.linkId;
	}

	public void setLinkId(Integer linkId) {
		this.linkId = linkId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
