<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="group" targetNamespace="http://service.divx.com/" xmlns:ns1="http://service.divx.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://service.divx.com/" schemaLocation="group_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="CreateGroupResponse">
    <wsdl:part name="parameters" element="ns1:CreateGroupResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateGroup">
    <wsdl:part name="parameters" element="ns1:CreateGroup">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="group">
    <wsdl:operation name="CreateGroup">
      <wsdl:input name="CreateGroup" message="ns1:CreateGroup">
    </wsdl:input>
      <wsdl:output name="CreateGroupResponse" message="ns1:CreateGroupResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
