package com.divx.service.domain.model;

// Generated 2015-4-2 23:00:14 by Hibernate Tools 4.3.1

/**
 * DcpCommentExt generated by hbm2java
 */
public class DcpCommentExt implements java.io.Serializable {

	private int commentId;
	private Integer replyCommentId;
	private Integer likecount;
	private Integer dislikecount;
	private String location;

	public DcpCommentExt() {
	}

	public DcpCommentExt(int commentId) {
		this.commentId = commentId;
	}

	public DcpCommentExt(int commentId, Integer replyCommentId,
			Integer likecount, Integer dislikecount, String location) {
		this.commentId = commentId;
		this.replyCommentId = replyCommentId;
		this.likecount = likecount;
		this.dislikecount = dislikecount;
		this.location = location;
	}

	public int getCommentId() {
		return this.commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	public Integer getReplyCommentId() {
		return this.replyCommentId;
	}

	public void setReplyCommentId(Integer replyCommentId) {
		this.replyCommentId = replyCommentId;
	}

	public Integer getLikecount() {
		return this.likecount;
	}

	public void setLikecount(Integer likecount) {
		this.likecount = likecount;
	}

	public Integer getDislikecount() {
		return this.dislikecount;
	}

	public void setDislikecount(Integer dislikecount) {
		this.dislikecount = dislikecount;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
