package com.divx.service.domain.model;

// Generated 2015-4-7 16:03:38 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpFriendRequest generated by hbm2java
 */
public class DcpFriendRequest implements java.io.Serializable {

	private Integer requestId;
	private int status;
	private Date datecreated;
	private Date dateresponse;
	private String content;
	private int requestUserid;
	private int receiveUserid;

	public DcpFriendRequest() {
	}

	public DcpFriendRequest(int status, Date datecreated, Date dateresponse,
			String content, int requestUserid, int receiveUserid) {
		this.status = status;
		this.datecreated = datecreated;
		this.dateresponse = dateresponse;
		this.content = content;
		this.requestUserid = requestUserid;
		this.receiveUserid = receiveUserid;
	}

	public Integer getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDateresponse() {
		return this.dateresponse;
	}

	public void setDateresponse(Date dateresponse) {
		this.dateresponse = dateresponse;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getRequestUserid() {
		return this.requestUserid;
	}

	public void setRequestUserid(int requestUserid) {
		this.requestUserid = requestUserid;
	}

	public int getReceiveUserid() {
		return this.receiveUserid;
	}

	public void setReceiveUserid(int receiveUserid) {
		this.receiveUserid = receiveUserid;
	}

}
