package com.divx.service.domain.model;

// Generated 2015-4-7 16:03:38 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpIntegration generated by hbm2java
 */
public class DcpIntegration implements java.io.Serializable {

	private Integer integrationId;
	private int userId;
	private Integer integration;
	private Date createDate;
	private Date modifyDate;

	public DcpIntegration() {
	}

	public DcpIntegration(int userId) {
		this.userId = userId;
	}

	public DcpIntegration(int userId, Integer integration, Date createDate,
			Date modifyDate) {
		this.userId = userId;
		this.integration = integration;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
	}

	public Integer getIntegrationId() {
		return this.integrationId;
	}

	public void setIntegrationId(Integer integrationId) {
		this.integrationId = integrationId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Integer getIntegration() {
		return this.integration;
	}

	public void setIntegration(Integer integration) {
		this.integration = integration;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
