package com.divx.service.domain.model;

// Generated 2015-6-23 12:26:37 by Hibernate Tools 4.3.1

/**
 * DcpLikeStat generated by hbm2java
 */
public class DcpLikeStat implements java.io.Serializable {

	private int mediaId;
	private int totalLikePoint;
	private int totalDislikePoint;

	public DcpLikeStat() {
	}

	public DcpLikeStat(int mediaId, int totalLikePoint, int totalDislikePoint) {
		this.mediaId = mediaId;
		this.totalLikePoint = totalLikePoint;
		this.totalDislikePoint = totalDislikePoint;
	}

	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	public int getTotalLikePoint() {
		return this.totalLikePoint;
	}

	public void setTotalLikePoint(int totalLikePoint) {
		this.totalLikePoint = totalLikePoint;
	}

	public int getTotalDislikePoint() {
		return this.totalDislikePoint;
	}

	public void setTotalDislikePoint(int totalDislikePoint) {
		this.totalDislikePoint = totalDislikePoint;
	}

}
