package com.divx.service.domain.model;

// Generated 2015-4-20 23:30:30 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpParty generated by hbm2java
 */
public class DcpParty implements java.io.Serializable {

	private Integer partyId;
	private int userId;
	private String title;
	private String description;
	private Date datecreated;
	private Date datemodified;
	private Date partydate;
	private String address;
	private Integer partytype;
	private Set dcpPartyUsers = new HashSet(0);

	public DcpParty() {
	}

	public DcpParty(int userId, String title) {
		this.userId = userId;
		this.title = title;
	}

	public DcpParty(int userId, String title, String description,
			Date datecreated, Date datemodified, Date partydate,
			String address, Integer partytype, Set dcpPartyUsers) {
		this.userId = userId;
		this.title = title;
		this.description = description;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.partydate = partydate;
		this.address = address;
		this.partytype = partytype;
		this.dcpPartyUsers = dcpPartyUsers;
	}

	public Integer getPartyId() {
		return this.partyId;
	}

	public void setPartyId(Integer partyId) {
		this.partyId = partyId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Date getPartydate() {
		return this.partydate;
	}

	public void setPartydate(Date partydate) {
		this.partydate = partydate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPartytype() {
		return this.partytype;
	}

	public void setPartytype(Integer partytype) {
		this.partytype = partytype;
	}

	public Set getDcpPartyUsers() {
		return this.dcpPartyUsers;
	}

	public void setDcpPartyUsers(Set dcpPartyUsers) {
		this.dcpPartyUsers = dcpPartyUsers;
	}

}
