package com.divx.service.domain.model;

// Generated 2015-6-23 12:26:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DcpShare generated by hbm2java
 */
public class DcpShare implements java.io.Serializable {

	private Integer shareId;
	private int mediaId;
	private int sharetype;
	private Date datecreated;
	private Date datemodified;
	private String mediatitle;
	private String mediadescription;
	private String snapshoturl;
	private Integer assettype;
	private Boolean deleted;
	private Integer status;
	private Integer contenttype;
	private String content;
	private Integer parentId;
	private Integer lessonId;
	private Set dcpShareUsers = new HashSet(0);

	public DcpShare() {
	}

	public DcpShare(int mediaId, int sharetype) {
		this.mediaId = mediaId;
		this.sharetype = sharetype;
	}

	public DcpShare(int mediaId, int sharetype, Date datecreated,
			Date datemodified, String mediatitle, String mediadescription,
			String snapshoturl, Integer assettype, Boolean deleted,
			Integer status, Integer contenttype, String content,
			Integer parentId, Integer lessonId, Set dcpShareUsers) {
		this.mediaId = mediaId;
		this.sharetype = sharetype;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.mediatitle = mediatitle;
		this.mediadescription = mediadescription;
		this.snapshoturl = snapshoturl;
		this.assettype = assettype;
		this.deleted = deleted;
		this.status = status;
		this.contenttype = contenttype;
		this.content = content;
		this.parentId = parentId;
		this.lessonId = lessonId;
		this.dcpShareUsers = dcpShareUsers;
	}

	public Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	public int getSharetype() {
		return this.sharetype;
	}

	public void setSharetype(int sharetype) {
		this.sharetype = sharetype;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public String getMediatitle() {
		return this.mediatitle;
	}

	public void setMediatitle(String mediatitle) {
		this.mediatitle = mediatitle;
	}

	public String getMediadescription() {
		return this.mediadescription;
	}

	public void setMediadescription(String mediadescription) {
		this.mediadescription = mediadescription;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public Integer getAssettype() {
		return this.assettype;
	}

	public void setAssettype(Integer assettype) {
		this.assettype = assettype;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(Integer contenttype) {
		this.contenttype = contenttype;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Integer lessonId) {
		this.lessonId = lessonId;
	}

	public Set getDcpShareUsers() {
		return this.dcpShareUsers;
	}

	public void setDcpShareUsers(Set dcpShareUsers) {
		this.dcpShareUsers = dcpShareUsers;
	}

}
