package com.divx.service.domain.model;

// Generated 2015-4-1 17:38:20 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpShare generated by hbm2java
 */
public class DcpShare implements java.io.Serializable {

	private Integer shareId;
	private int mediaId;
	private int userId;
	private int sharetype;
	private Integer friendId;
	private Integer groupId;
	private Date datecreated;
	private Date datemodified;
	private String mediatitle;
	private String mediadescription;
	private String snapshoturl;
	private Integer assettype;
	private Boolean deleted;
	private Integer status;
	private Integer contenttype;
	private String content;

	public DcpShare() {
	}

	public DcpShare(int mediaId, int userId, int sharetype) {
		this.mediaId = mediaId;
		this.userId = userId;
		this.sharetype = sharetype;
	}

	public DcpShare(int mediaId, int userId, int sharetype, Integer friendId,
			Integer groupId, Date datecreated, Date datemodified,
			String mediatitle, String mediadescription, String snapshoturl,
			Integer assettype, Boolean deleted, Integer status,
			Integer contenttype, String content) {
		this.mediaId = mediaId;
		this.userId = userId;
		this.sharetype = sharetype;
		this.friendId = friendId;
		this.groupId = groupId;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.mediatitle = mediatitle;
		this.mediadescription = mediadescription;
		this.snapshoturl = snapshoturl;
		this.assettype = assettype;
		this.deleted = deleted;
		this.status = status;
		this.contenttype = contenttype;
		this.content = content;
	}

	public Integer getShareId() {
		return this.shareId;
	}

	public void setShareId(Integer shareId) {
		this.shareId = shareId;
	}

	public int getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(int mediaId) {
		this.mediaId = mediaId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getSharetype() {
		return this.sharetype;
	}

	public void setSharetype(int sharetype) {
		this.sharetype = sharetype;
	}

	public Integer getFriendId() {
		return this.friendId;
	}

	public void setFriendId(Integer friendId) {
		this.friendId = friendId;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public String getMediatitle() {
		return this.mediatitle;
	}

	public void setMediatitle(String mediatitle) {
		this.mediatitle = mediatitle;
	}

	public String getMediadescription() {
		return this.mediadescription;
	}

	public void setMediadescription(String mediadescription) {
		this.mediadescription = mediadescription;
	}

	public String getSnapshoturl() {
		return this.snapshoturl;
	}

	public void setSnapshoturl(String snapshoturl) {
		this.snapshoturl = snapshoturl;
	}

	public Integer getAssettype() {
		return this.assettype;
	}

	public void setAssettype(Integer assettype) {
		this.assettype = assettype;
	}

	public Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getContenttype() {
		return this.contenttype;
	}

	public void setContenttype(Integer contenttype) {
		this.contenttype = contenttype;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
