package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfAuthorizations generated by hbm2java
 */
public class OsfAuthorizations implements java.io.Serializable {

	private Long id;
	private String secret;
	private String target;
	private String token;
	private long userId;

	public OsfAuthorizations() {
	}

	public OsfAuthorizations(String secret, String target, String token,
			long userId) {
		this.secret = secret;
		this.target = target;
		this.token = token;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
