package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfAnswers generated by hbm2java
 */
public class OsfAnswers implements java.io.Serializable {

	private Long id;
	private String content;
	private Date entered;
	private Date modified;
	private long enteredById;
	private long modifiedById;
	private long questionId;
	private Long useful;
	private Long useless;
	private Long votes;

	public OsfAnswers() {
	}

	public OsfAnswers(String content, long enteredById, long modifiedById,
			long questionId) {
		this.content = content;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.questionId = questionId;
	}

	public OsfAnswers(String content, Date entered, Date modified,
			long enteredById, long modifiedById, long questionId, Long useful,
			Long useless, Long votes) {
		this.content = content;
		this.entered = entered;
		this.modified = modified;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.questionId = questionId;
		this.useful = useful;
		this.useless = useless;
		this.votes = votes;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(long questionId) {
		this.questionId = questionId;
	}

	public Long getUseful() {
		return this.useful;
	}

	public void setUseful(Long useful) {
		this.useful = useful;
	}

	public Long getUseless() {
		return this.useless;
	}

	public void setUseless(Long useless) {
		this.useless = useless;
	}

	public Long getVotes() {
		return this.votes;
	}

	public void setVotes(Long votes) {
		this.votes = votes;
	}

}
