package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfAttachments generated by hbm2java
 */
public class OsfAttachments implements java.io.Serializable {

	private Long id;
	private String contentType;
	private Date entered;
	private String fileName;
	private Long size;

	public OsfAttachments() {
	}

	public OsfAttachments(String contentType, String fileName) {
		this.contentType = contentType;
		this.fileName = fileName;
	}

	public OsfAttachments(String contentType, Date entered, String fileName,
			Long size) {
		this.contentType = contentType;
		this.entered = entered;
		this.fileName = fileName;
		this.size = size;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Long getSize() {
		return this.size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

}
