package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfActivities generated by hbm2java
 */
public class OsfActivities implements java.io.Serializable {

	private Long id;
	private String description;
	private Date entered;
	private String entity;
	private String format;
	private Long linkedId;
	private Date modified;
	private String type;
	private Long enteredById;
	private Long parentId;
	private Long projectId;

	public OsfActivities() {
	}

	public OsfActivities(String description, Date entered, String format,
			Date modified, String type) {
		this.description = description;
		this.entered = entered;
		this.format = format;
		this.modified = modified;
		this.type = type;
	}

	public OsfActivities(String description, Date entered, String entity,
			String format, Long linkedId, Date modified, String type,
			Long enteredById, Long parentId, Long projectId) {
		this.description = description;
		this.entered = entered;
		this.entity = entity;
		this.format = format;
		this.linkedId = linkedId;
		this.modified = modified;
		this.type = type;
		this.enteredById = enteredById;
		this.parentId = parentId;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public Long getLinkedId() {
		return this.linkedId;
	}

	public void setLinkedId(Long linkedId) {
		this.linkedId = linkedId;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(Long enteredById) {
		this.enteredById = enteredById;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

}
