package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfAlbums generated by hbm2java
 */
public class OsfAlbums implements java.io.Serializable {

	private Long id;
	private Date entered;
	private Date modified;
	private String name;
	private long enteredById;
	private long modifiedById;
	private long projectId;

	public OsfAlbums() {
	}

	public OsfAlbums(String name, long enteredById, long modifiedById,
			long projectId) {
		this.name = name;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfAlbums(Date entered, Date modified, String name,
			long enteredById, long modifiedById, long projectId) {
		this.entered = entered;
		this.modified = modified;
		this.name = name;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
