package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfEvents generated by hbm2java
 */
public class OsfEvents implements java.io.Serializable {

	private Long id;
	private Boolean allDay;
	private String description;
	private Boolean enabled;
	private Date endDate;
	private Date entered;
	private Date modified;
	private Date startDate;
	private String title;
	private String type;
	private String url;
	private long enteredById;
	private long modifiedById;
	private long projectId;

	public OsfEvents() {
	}

	public OsfEvents(Date endDate, Date entered, Date modified, Date startDate,
			String title, String type, long enteredById, long modifiedById,
			long projectId) {
		this.endDate = endDate;
		this.entered = entered;
		this.modified = modified;
		this.startDate = startDate;
		this.title = title;
		this.type = type;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfEvents(Boolean allDay, String description, Boolean enabled,
			Date endDate, Date entered, Date modified, Date startDate,
			String title, String type, String url, long enteredById,
			long modifiedById, long projectId) {
		this.allDay = allDay;
		this.description = description;
		this.enabled = enabled;
		this.endDate = endDate;
		this.entered = entered;
		this.modified = modified;
		this.startDate = startDate;
		this.title = title;
		this.type = type;
		this.url = url;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getAllDay() {
		return this.allDay;
	}

	public void setAllDay(Boolean allDay) {
		this.allDay = allDay;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
