package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfFiles generated by hbm2java
 */
public class OsfFiles implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private Date entered;
	private Date modified;
	private String name;
	private Long enteredById;
	private Long folderId;
	private long modifiedById;
	private Long realFileId;
	private Boolean featured;

	public OsfFiles() {
	}

	public OsfFiles(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public OsfFiles(Boolean enabled, Date entered, Date modified, String name,
			Long enteredById, Long folderId, long modifiedById,
			Long realFileId, Boolean featured) {
		this.enabled = enabled;
		this.entered = entered;
		this.modified = modified;
		this.name = name;
		this.enteredById = enteredById;
		this.folderId = folderId;
		this.modifiedById = modifiedById;
		this.realFileId = realFileId;
		this.featured = featured;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(Long enteredById) {
		this.enteredById = enteredById;
	}

	public Long getFolderId() {
		return this.folderId;
	}

	public void setFolderId(Long folderId) {
		this.folderId = folderId;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public Long getRealFileId() {
		return this.realFileId;
	}

	public void setRealFileId(Long realFileId) {
		this.realFileId = realFileId;
	}

	public Boolean getFeatured() {
		return this.featured;
	}

	public void setFeatured(Boolean featured) {
		this.featured = featured;
	}

}
