package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfKeywords generated by hbm2java
 */
public class OsfKeywords implements java.io.Serializable {

	private Long id;
	private Date entered;
	private String keyword;
	private long number;
	private String type;
	private Long categoryId;
	private Long enteredById;

	public OsfKeywords() {
	}

	public OsfKeywords(String keyword, long number, String type) {
		this.keyword = keyword;
		this.number = number;
		this.type = type;
	}

	public OsfKeywords(Date entered, String keyword, long number, String type,
			Long categoryId, Long enteredById) {
		this.entered = entered;
		this.keyword = keyword;
		this.number = number;
		this.type = type;
		this.categoryId = categoryId;
		this.enteredById = enteredById;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public long getNumber() {
		return this.number;
	}

	public void setNumber(long number) {
		this.number = number;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public Long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(Long enteredById) {
		this.enteredById = enteredById;
	}

}
