package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfLinks generated by hbm2java
 */
public class OsfLinks implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private String entity;
	private String title;
	private long toId;
	private long fromId;
	private String type;
	private Date entered;

	public OsfLinks() {
	}

	public OsfLinks(String entity, long toId, long fromId) {
		this.entity = entity;
		this.toId = toId;
		this.fromId = fromId;
	}

	public OsfLinks(Boolean enabled, String entity, String title, long toId,
			long fromId, String type, Date entered) {
		this.enabled = enabled;
		this.entity = entity;
		this.title = title;
		this.toId = toId;
		this.fromId = fromId;
		this.type = type;
		this.entered = entered;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public long getToId() {
		return this.toId;
	}

	public void setToId(long toId) {
		this.toId = toId;
	}

	public long getFromId() {
		return this.fromId;
	}

	public void setFromId(long fromId) {
		this.fromId = fromId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

}
