package com.divx.service.domain.model;

// Generated 2015-4-20 23:30:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfMessages generated by hbm2java
 */
public class OsfMessages implements java.io.Serializable {

	private Long id;
	private String content;
	private Date entered;
	private Boolean read;
	private String subject;
	private long enteredById;
	private long fromId;
	private Long readById;
	private long toId;

	public OsfMessages() {
	}

	public OsfMessages(String content, Date entered, String subject,
			long enteredById, long fromId, long toId) {
		this.content = content;
		this.entered = entered;
		this.subject = subject;
		this.enteredById = enteredById;
		this.fromId = fromId;
		this.toId = toId;
	}

	public OsfMessages(String content, Date entered, Boolean read,
			String subject, long enteredById, long fromId, Long readById,
			long toId) {
		this.content = content;
		this.entered = entered;
		this.read = read;
		this.subject = subject;
		this.enteredById = enteredById;
		this.fromId = fromId;
		this.readById = readById;
		this.toId = toId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Boolean getRead() {
		return this.read;
	}

	public void setRead(Boolean read) {
		this.read = read;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getFromId() {
		return this.fromId;
	}

	public void setFromId(long fromId) {
		this.fromId = fromId;
	}

	public Long getReadById() {
		return this.readById;
	}

	public void setReadById(Long readById) {
		this.readById = readById;
	}

	public long getToId() {
		return this.toId;
	}

	public void setToId(long toId) {
		this.toId = toId;
	}

}
