package com.divx.service.domain.model;

// Generated 2014-11-5 15:29:19 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfMailSettings generated by hbm2java
 */
public class OsfMailSettings implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private int servertype;
	private String host;
	private Integer port;
	private String password;
	private String username;
	private String email;
	private Date datecreated;
	private Date datemodified;

	public OsfMailSettings() {
	}

	public OsfMailSettings(int servertype, String username, String email) {
		this.servertype = servertype;
		this.username = username;
		this.email = email;
	}

	public OsfMailSettings(Boolean enabled, int servertype, String host,
			Integer port, String password, String username, String email,
			Date datecreated, Date datemodified) {
		this.enabled = enabled;
		this.servertype = servertype;
		this.host = host;
		this.port = port;
		this.password = password;
		this.username = username;
		this.email = email;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public int getServertype() {
		return this.servertype;
	}

	public void setServertype(int servertype) {
		this.servertype = servertype;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

}
