package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfMarkers generated by hbm2java
 */
public class OsfMarkers implements java.io.Serializable {

	private Long id;
	private String description;
	private Boolean draggable;
	private Boolean enabled;
	private String latitude;
	private String longitude;
	private Long iconId;
	private Long mapId;

	public OsfMarkers() {
	}

	public OsfMarkers(String description, Boolean draggable, Boolean enabled,
			String latitude, String longitude, Long iconId, Long mapId) {
		this.description = description;
		this.draggable = draggable;
		this.enabled = enabled;
		this.latitude = latitude;
		this.longitude = longitude;
		this.iconId = iconId;
		this.mapId = mapId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getDraggable() {
		return this.draggable;
	}

	public void setDraggable(Boolean draggable) {
		this.draggable = draggable;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public Long getIconId() {
		return this.iconId;
	}

	public void setIconId(Long iconId) {
		this.iconId = iconId;
	}

	public Long getMapId() {
		return this.mapId;
	}

	public void setMapId(Long mapId) {
		this.mapId = mapId;
	}

}
