package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfMaps generated by hbm2java
 */
public class OsfMaps implements java.io.Serializable {

	private Long id;
	private Integer depth;
	private String latitude;
	private String longitude;
	private Boolean scrollable;
	private Boolean showSearch;
	private Boolean showStreet;
	private Boolean showTraffic;
	private Long projectId;

	public OsfMaps() {
	}

	public OsfMaps(Integer depth, String latitude, String longitude,
			Boolean scrollable, Boolean showSearch, Boolean showStreet,
			Boolean showTraffic, Long projectId) {
		this.depth = depth;
		this.latitude = latitude;
		this.longitude = longitude;
		this.scrollable = scrollable;
		this.showSearch = showSearch;
		this.showStreet = showStreet;
		this.showTraffic = showTraffic;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getDepth() {
		return this.depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public Boolean getScrollable() {
		return this.scrollable;
	}

	public void setScrollable(Boolean scrollable) {
		this.scrollable = scrollable;
	}

	public Boolean getShowSearch() {
		return this.showSearch;
	}

	public void setShowSearch(Boolean showSearch) {
		this.showSearch = showSearch;
	}

	public Boolean getShowStreet() {
		return this.showStreet;
	}

	public void setShowStreet(Boolean showStreet) {
		this.showStreet = showStreet;
	}

	public Boolean getShowTraffic() {
		return this.showTraffic;
	}

	public void setShowTraffic(Boolean showTraffic) {
		this.showTraffic = showTraffic;
	}

	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

}
