package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfProfiles generated by hbm2java
 */
public class OsfProfiles implements java.io.Serializable {

	private Long id;
	private String attributes;
	private String description;
	private Date entered;
	private Date modified;
	private String shortDescription;
	private String title;
	private long enteredById;
	private Long logoId;
	private long modifiedById;
	private long projectId;

	public OsfProfiles() {
	}

	public OsfProfiles(String title, long enteredById, long modifiedById,
			long projectId) {
		this.title = title;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfProfiles(String attributes, String description, Date entered,
			Date modified, String shortDescription, String title,
			long enteredById, Long logoId, long modifiedById, long projectId) {
		this.attributes = attributes;
		this.description = description;
		this.entered = entered;
		this.modified = modified;
		this.shortDescription = shortDescription;
		this.title = title;
		this.enteredById = enteredById;
		this.logoId = logoId;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAttributes() {
		return this.attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public Long getLogoId() {
		return this.logoId;
	}

	public void setLogoId(Long logoId) {
		this.logoId = logoId;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
