package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfPostCategories generated by hbm2java
 */
public class OsfPostCategories implements java.io.Serializable {

	private Long id;
	private String code;
	private Boolean enabled;
	private String label;
	private Integer level;
	private long projectId;

	public OsfPostCategories() {
	}

	public OsfPostCategories(String label, long projectId) {
		this.label = label;
		this.projectId = projectId;
	}

	public OsfPostCategories(String code, Boolean enabled, String label,
			Integer level, long projectId) {
		this.code = code;
		this.enabled = enabled;
		this.label = label;
		this.level = level;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
