package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfPermissions generated by hbm2java
 */
public class OsfPermissions implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private long categoryId;
	private long resourceId;
	private long roleId;

	public OsfPermissions() {
	}

	public OsfPermissions(long categoryId, long resourceId, long roleId) {
		this.categoryId = categoryId;
		this.resourceId = resourceId;
		this.roleId = roleId;
	}

	public OsfPermissions(Boolean enabled, long categoryId, long resourceId,
			long roleId) {
		this.enabled = enabled;
		this.categoryId = categoryId;
		this.resourceId = resourceId;
		this.roleId = roleId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(long resourceId) {
		this.resourceId = resourceId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

}
