package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfPosts generated by hbm2java
 */
public class OsfPosts implements java.io.Serializable {

	private Long id;
	private String content;
	private Boolean enabled;
	private Date entered;
	private String keywords;
	private Date modified;
	private String title;
	private Boolean top;
	private String type;
	private Long categoryId;
	private long enteredById;
	private long modifiedById;
	private long projectId;

	public OsfPosts() {
	}

	public OsfPosts(String content, String title, String type,
			long enteredById, long modifiedById, long projectId) {
		this.content = content;
		this.title = title;
		this.type = type;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfPosts(String content, Boolean enabled, Date entered,
			String keywords, Date modified, String title, Boolean top,
			String type, Long categoryId, long enteredById, long modifiedById,
			long projectId) {
		this.content = content;
		this.enabled = enabled;
		this.entered = entered;
		this.keywords = keywords;
		this.modified = modified;
		this.title = title;
		this.top = top;
		this.type = type;
		this.categoryId = categoryId;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getTop() {
		return this.top;
	}

	public void setTop(Boolean top) {
		this.top = top;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
