package com.divx.service.domain.model;

// Generated 2015-4-2 23:00:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfProjects generated by hbm2java
 */
public class OsfProjects implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private Date entered;
	private Date modified;
	private Boolean publish;
	private String title;
	private String uniqueId;
	private long categoryId;
	private Long enteredById;
	private Long modifiedById;
	private Long subCategory1Id;
	private Long subCategory2Id;
	private Long subCategory3Id;
	private String description;
	private String photourl;

	public OsfProjects() {
	}

	public OsfProjects(Date entered, Date modified, String title,
			String uniqueId, long categoryId) {
		this.entered = entered;
		this.modified = modified;
		this.title = title;
		this.uniqueId = uniqueId;
		this.categoryId = categoryId;
	}

	public OsfProjects(Boolean enabled, Date entered, Date modified,
			Boolean publish, String title, String uniqueId, long categoryId,
			Long enteredById, Long modifiedById, Long subCategory1Id,
			Long subCategory2Id, Long subCategory3Id, String description,
			String photourl) {
		this.enabled = enabled;
		this.entered = entered;
		this.modified = modified;
		this.publish = publish;
		this.title = title;
		this.uniqueId = uniqueId;
		this.categoryId = categoryId;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.subCategory1Id = subCategory1Id;
		this.subCategory2Id = subCategory2Id;
		this.subCategory3Id = subCategory3Id;
		this.description = description;
		this.photourl = photourl;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Boolean getPublish() {
		return this.publish;
	}

	public void setPublish(Boolean publish) {
		this.publish = publish;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public Long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(Long enteredById) {
		this.enteredById = enteredById;
	}

	public Long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public Long getSubCategory1Id() {
		return this.subCategory1Id;
	}

	public void setSubCategory1Id(Long subCategory1Id) {
		this.subCategory1Id = subCategory1Id;
	}

	public Long getSubCategory2Id() {
		return this.subCategory2Id;
	}

	public void setSubCategory2Id(Long subCategory2Id) {
		this.subCategory2Id = subCategory2Id;
	}

	public Long getSubCategory3Id() {
		return this.subCategory3Id;
	}

	public void setSubCategory3Id(Long subCategory3Id) {
		this.subCategory3Id = subCategory3Id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPhotourl() {
		return this.photourl;
	}

	public void setPhotourl(String photourl) {
		this.photourl = photourl;
	}

}
