package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfProjectFeatures generated by hbm2java
 */
public class OsfProjectFeatures implements java.io.Serializable {

	private Long id;
	private String code;
	private String label;
	private Integer level;
	private Boolean show;
	private long projectId;
	private long roleId;

	public OsfProjectFeatures() {
	}

	public OsfProjectFeatures(String code, long projectId, long roleId) {
		this.code = code;
		this.projectId = projectId;
		this.roleId = roleId;
	}

	public OsfProjectFeatures(String code, String label, Integer level,
			Boolean show, long projectId, long roleId) {
		this.code = code;
		this.label = label;
		this.level = level;
		this.show = show;
		this.projectId = projectId;
		this.roleId = roleId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Boolean getShow() {
		return this.show;
	}

	public void setShow(Boolean show) {
		this.show = show;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

}
