package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfProjectCategories generated by hbm2java
 */
public class OsfProjectCategories implements java.io.Serializable {

	private Long id;
	private String code;
	private Boolean enabled;
	private String label;
	private Integer level;
	private Boolean sensitive;
	private long siteId;
	private Long parentId;

	public OsfProjectCategories() {
	}

	public OsfProjectCategories(String code, String label, long siteId) {
		this.code = code;
		this.label = label;
		this.siteId = siteId;
	}

	public OsfProjectCategories(String code, Boolean enabled, String label,
			Integer level, Boolean sensitive, long siteId, Long parentId) {
		this.code = code;
		this.enabled = enabled;
		this.label = label;
		this.level = level;
		this.sensitive = sensitive;
		this.siteId = siteId;
		this.parentId = parentId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Boolean getSensitive() {
		return this.sensitive;
	}

	public void setSensitive(Boolean sensitive) {
		this.sensitive = sensitive;
	}

	public long getSiteId() {
		return this.siteId;
	}

	public void setSiteId(long siteId) {
		this.siteId = siteId;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

}
