package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfQuestions generated by hbm2java
 */
public class OsfQuestions implements java.io.Serializable {

	private Long id;
	private String content;
	private Date entered;
	private Date modified;
	private String title;
	private Long answerId;
	private long enteredById;
	private long modifiedById;
	private long projectId;
	private Long views;
	private Long votes;
	private Integer answersSize;

	public OsfQuestions() {
	}

	public OsfQuestions(String content, String title, long enteredById,
			long modifiedById, long projectId) {
		this.content = content;
		this.title = title;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfQuestions(String content, Date entered, Date modified,
			String title, Long answerId, long enteredById, long modifiedById,
			long projectId, Long views, Long votes, Integer answersSize) {
		this.content = content;
		this.entered = entered;
		this.modified = modified;
		this.title = title;
		this.answerId = answerId;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
		this.views = views;
		this.votes = votes;
		this.answersSize = answersSize;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Long answerId) {
		this.answerId = answerId;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	public Long getViews() {
		return this.views;
	}

	public void setViews(Long views) {
		this.views = views;
	}

	public Long getVotes() {
		return this.votes;
	}

	public void setVotes(Long votes) {
		this.votes = votes;
	}

	public Integer getAnswersSize() {
		return this.answersSize;
	}

	public void setAnswersSize(Integer answersSize) {
		this.answersSize = answersSize;
	}

}
