package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfResources generated by hbm2java
 */
public class OsfResources implements java.io.Serializable {

	private Long id;
	private String code;
	private String description;
	private Boolean enabled;
	private String name;

	public OsfResources() {
	}

	public OsfResources(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public OsfResources(String code, String description, Boolean enabled,
			String name) {
		this.code = code;
		this.description = description;
		this.enabled = enabled;
		this.name = name;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
