package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfReplies generated by hbm2java
 */
public class OsfReplies implements java.io.Serializable {

	private Long id;
	private String content;
	private Boolean enabled;
	private Date entered;
	private Date modified;
	private String subject;
	private long enteredById;
	private Long modifiedById;
	private Long quoteId;
	private long topicId;

	public OsfReplies() {
	}

	public OsfReplies(String content, Date entered, String subject,
			long enteredById, long topicId) {
		this.content = content;
		this.entered = entered;
		this.subject = subject;
		this.enteredById = enteredById;
		this.topicId = topicId;
	}

	public OsfReplies(String content, Boolean enabled, Date entered,
			Date modified, String subject, long enteredById, Long modifiedById,
			Long quoteId, long topicId) {
		this.content = content;
		this.enabled = enabled;
		this.entered = entered;
		this.modified = modified;
		this.subject = subject;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.quoteId = quoteId;
		this.topicId = topicId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public Long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(Long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public Long getQuoteId() {
		return this.quoteId;
	}

	public void setQuoteId(Long quoteId) {
		this.quoteId = quoteId;
	}

	public long getTopicId() {
		return this.topicId;
	}

	public void setTopicId(long topicId) {
		this.topicId = topicId;
	}

}
