package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfRating generated by hbm2java
 */
public class OsfRating implements java.io.Serializable {

	private Long id;
	private String comment;
	private Date entered;
	private Date modified;
	private int rating;
	private long enteredById;
	private long modifiedById;
	private long projectId;

	public OsfRating() {
	}

	public OsfRating(String comment, Date entered, int rating,
			long enteredById, long modifiedById, long projectId) {
		this.comment = comment;
		this.entered = entered;
		this.rating = rating;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public OsfRating(String comment, Date entered, Date modified, int rating,
			long enteredById, long modifiedById, long projectId) {
		this.comment = comment;
		this.entered = entered;
		this.modified = modified;
		this.rating = rating;
		this.enteredById = enteredById;
		this.modifiedById = modifiedById;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
