package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfSiteLinks generated by hbm2java
 */
public class OsfSiteLinks implements java.io.Serializable {

	private Long id;
	private String code;
	private String href;
	private String text;
	private long siteId;

	public OsfSiteLinks() {
	}

	public OsfSiteLinks(long siteId) {
		this.siteId = siteId;
	}

	public OsfSiteLinks(String code, String href, String text, long siteId) {
		this.code = code;
		this.href = href;
		this.text = text;
		this.siteId = siteId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public long getSiteId() {
		return this.siteId;
	}

	public void setSiteId(long siteId) {
		this.siteId = siteId;
	}

}
