package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfSites generated by hbm2java
 */
public class OsfSites implements java.io.Serializable {

	private Long id;
	private String contextPath;
	private String copyright;
	private String description;
	private String domain;
	private Boolean enabled;
	private String keywords;
	private Integer port;
	private Boolean ssl;
	private String title;
	private Long mailSettingsId;
	private Long themeId;

	public OsfSites() {
	}

	public OsfSites(String contextPath, String domain, String title) {
		this.contextPath = contextPath;
		this.domain = domain;
		this.title = title;
	}

	public OsfSites(String contextPath, String copyright, String description,
			String domain, Boolean enabled, String keywords, Integer port,
			Boolean ssl, String title, Long mailSettingsId, Long themeId) {
		this.contextPath = contextPath;
		this.copyright = copyright;
		this.description = description;
		this.domain = domain;
		this.enabled = enabled;
		this.keywords = keywords;
		this.port = port;
		this.ssl = ssl;
		this.title = title;
		this.mailSettingsId = mailSettingsId;
		this.themeId = themeId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContextPath() {
		return this.contextPath;
	}

	public void setContextPath(String contextPath) {
		this.contextPath = contextPath;
	}

	public String getCopyright() {
		return this.copyright;
	}

	public void setCopyright(String copyright) {
		this.copyright = copyright;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	public Boolean getSsl() {
		return this.ssl;
	}

	public void setSsl(Boolean ssl) {
		this.ssl = ssl;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Long getMailSettingsId() {
		return this.mailSettingsId;
	}

	public void setMailSettingsId(Long mailSettingsId) {
		this.mailSettingsId = mailSettingsId;
	}

	public Long getThemeId() {
		return this.themeId;
	}

	public void setThemeId(Long themeId) {
		this.themeId = themeId;
	}

}
