package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfStatistics generated by hbm2java
 */
public class OsfStatistics implements java.io.Serializable {

	private Long id;
	private Long count;
	private String entity;
	private long linkedId;
	private long projectId;
	private String type;

	public OsfStatistics() {
	}

	public OsfStatistics(long linkedId, long projectId) {
		this.linkedId = linkedId;
		this.projectId = projectId;
	}

	public OsfStatistics(Long count, String entity, long linkedId,
			long projectId, String type) {
		this.count = count;
		this.entity = entity;
		this.linkedId = linkedId;
		this.projectId = projectId;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public long getLinkedId() {
		return this.linkedId;
	}

	public void setLinkedId(long linkedId) {
		this.linkedId = linkedId;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
