package com.divx.service.domain.model;

// Generated 2015-4-20 23:30:30 by Hibernate Tools 4.3.1

/**
 * OsfTeamMembers generated by hbm2java
 */
public class OsfTeamMembers implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private String status;
	private long projectId;
	private long roleId;
	private long userId;
	private String nickname;
	private String photourl;
	private String username;

	public OsfTeamMembers() {
	}

	public OsfTeamMembers(long projectId, long roleId, long userId) {
		this.projectId = projectId;
		this.roleId = roleId;
		this.userId = userId;
	}

	public OsfTeamMembers(Boolean enabled, String status, long projectId,
			long roleId, long userId, String nickname, String photourl,
			String username) {
		this.enabled = enabled;
		this.status = status;
		this.projectId = projectId;
		this.roleId = roleId;
		this.userId = userId;
		this.nickname = nickname;
		this.photourl = photourl;
		this.username = username;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPhotourl() {
		return this.photourl;
	}

	public void setPhotourl(String photourl) {
		this.photourl = photourl;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
