package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfTopicCategories generated by hbm2java
 */
public class OsfTopicCategories implements java.io.Serializable {

	private Long id;
	private Boolean enabled;
	private String label;
	private long projectId;

	public OsfTopicCategories() {
	}

	public OsfTopicCategories(String label, long projectId) {
		this.label = label;
		this.projectId = projectId;
	}

	public OsfTopicCategories(Boolean enabled, String label, long projectId) {
		this.enabled = enabled;
		this.label = label;
		this.projectId = projectId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

}
