package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfTopics generated by hbm2java
 */
public class OsfTopics implements java.io.Serializable {

	private Long id;
	private String content;
	private Boolean enabled;
	private Date entered;
	private Date modified;
	private Boolean question;
	private String subject;
	private Long answerId;
	private Long categoryId;
	private long enteredById;
	private long forumId;
	private long modifiedById;

	public OsfTopics() {
	}

	public OsfTopics(String content, Date entered, Date modified,
			String subject, long enteredById, long forumId, long modifiedById) {
		this.content = content;
		this.entered = entered;
		this.modified = modified;
		this.subject = subject;
		this.enteredById = enteredById;
		this.forumId = forumId;
		this.modifiedById = modifiedById;
	}

	public OsfTopics(String content, Boolean enabled, Date entered,
			Date modified, Boolean question, String subject, Long answerId,
			Long categoryId, long enteredById, long forumId, long modifiedById) {
		this.content = content;
		this.enabled = enabled;
		this.entered = entered;
		this.modified = modified;
		this.question = question;
		this.subject = subject;
		this.answerId = answerId;
		this.categoryId = categoryId;
		this.enteredById = enteredById;
		this.forumId = forumId;
		this.modifiedById = modifiedById;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public Boolean getQuestion() {
		return this.question;
	}

	public void setQuestion(Boolean question) {
		this.question = question;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Long getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Long answerId) {
		this.answerId = answerId;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public long getEnteredById() {
		return this.enteredById;
	}

	public void setEnteredById(long enteredById) {
		this.enteredById = enteredById;
	}

	public long getForumId() {
		return this.forumId;
	}

	public void setForumId(long forumId) {
		this.forumId = forumId;
	}

	public long getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(long modifiedById) {
		this.modifiedById = modifiedById;
	}

}
