package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

/**
 * OsfTemplates generated by hbm2java
 */
public class OsfTemplates implements java.io.Serializable {

	private Long id;
	private String code;
	private String content;
	private Boolean enabled;
	private String name;
	private Long categoryId;

	public OsfTemplates() {
	}

	public OsfTemplates(String code, String content, String name) {
		this.code = code;
		this.content = content;
		this.name = name;
	}

	public OsfTemplates(String code, String content, Boolean enabled,
			String name, Long categoryId) {
		this.code = code;
		this.content = content;
		this.enabled = enabled;
		this.name = name;
		this.categoryId = categoryId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

}
