package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfTags generated by hbm2java
 */
public class OsfTags implements java.io.Serializable {

	private Long id;
	private String entity;
	private long linkedId;
	private String name;
	private Date entered;
	private long userId;

	public OsfTags() {
	}

	public OsfTags(String entity, long linkedId, String name, long userId) {
		this.entity = entity;
		this.linkedId = linkedId;
		this.name = name;
		this.userId = userId;
	}

	public OsfTags(String entity, long linkedId, String name, Date entered,
			long userId) {
		this.entity = entity;
		this.linkedId = linkedId;
		this.name = name;
		this.entered = entered;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public long getLinkedId() {
		return this.linkedId;
	}

	public void setLinkedId(long linkedId) {
		this.linkedId = linkedId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
