package com.divx.service.domain.model;

// Generated 2014-11-4 15:36:18 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * OsfVoteRecords generated by hbm2java
 */
public class OsfVoteRecords implements java.io.Serializable {

	private Long id;
	private String code;
	private Date entered;
	private String entity;
	private long linkedId;
	private long userId;

	public OsfVoteRecords() {
	}

	public OsfVoteRecords(String code, String entity, long linkedId, long userId) {
		this.code = code;
		this.entity = entity;
		this.linkedId = linkedId;
		this.userId = userId;
	}

	public OsfVoteRecords(String code, Date entered, String entity,
			long linkedId, long userId) {
		this.code = code;
		this.entered = entered;
		this.entity = entity;
		this.linkedId = linkedId;
		this.userId = userId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getEntered() {
		return this.entered;
	}

	public void setEntered(Date entered) {
		this.entered = entered;
	}

	public String getEntity() {
		return this.entity;
	}

	public void setEntity(String entity) {
		this.entity = entity;
	}

	public long getLinkedId() {
		return this.linkedId;
	}

	public void setLinkedId(long linkedId) {
		this.linkedId = linkedId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

}
