package com.divx.service.domain.model;

// Generated 2015-4-3 16:12:38 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpFilter generated by hbm2java
 */
public class DcpFilter implements java.io.Serializable {

	private Integer filterId;
	private int width;
	private int height;
	private int format;
	private int rotation;
	private String filterName;
	private String filterContent;
	private Date dateCreate;
	private Date dateModify;
	private Boolean enabled;

	public DcpFilter() {
	}

	public DcpFilter(int width, int height, int format, int rotation,
			String filterName) {
		this.width = width;
		this.height = height;
		this.format = format;
		this.rotation = rotation;
		this.filterName = filterName;
	}

	public DcpFilter(int width, int height, int format, int rotation,
			String filterName, String filterContent, Date dateCreate,
			Date dateModify, Boolean enabled) {
		this.width = width;
		this.height = height;
		this.format = format;
		this.rotation = rotation;
		this.filterName = filterName;
		this.filterContent = filterContent;
		this.dateCreate = dateCreate;
		this.dateModify = dateModify;
		this.enabled = enabled;
	}

	public Integer getFilterId() {
		return this.filterId;
	}

	public void setFilterId(Integer filterId) {
		this.filterId = filterId;
	}

	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public int getFormat() {
		return this.format;
	}

	public void setFormat(int format) {
		this.format = format;
	}

	public int getRotation() {
		return this.rotation;
	}

	public void setRotation(int rotation) {
		this.rotation = rotation;
	}

	public String getFilterName() {
		return this.filterName;
	}

	public void setFilterName(String filterName) {
		this.filterName = filterName;
	}

	public String getFilterContent() {
		return this.filterContent;
	}

	public void setFilterContent(String filterContent) {
		this.filterContent = filterContent;
	}

	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	public Date getDateModify() {
		return this.dateModify;
	}

	public void setDateModify(Date dateModify) {
		this.dateModify = dateModify;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

}
