package com.divx.service.domain.model;

// Generated 2015-2-5 15:50:16 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpPresetgroup generated by hbm2java
 */
public class DcpPresetgroup implements java.io.Serializable {

	private Integer pgId;
	private DcpRadio dcpRadio;
	private Integer width;
	private Integer height;
	private Float framerate;
	private Integer format;
	private String pgname;
	private Date datecreated;
	private Date datemodified;
	private Boolean enable;

	public DcpPresetgroup() {
	}

	public DcpPresetgroup(DcpRadio dcpRadio, Integer width, Integer height,
			Float framerate, Integer format, String pgname, Date datecreated,
			Date datemodified, Boolean enable) {
		this.dcpRadio = dcpRadio;
		this.width = width;
		this.height = height;
		this.framerate = framerate;
		this.format = format;
		this.pgname = pgname;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.enable = enable;
	}

	public Integer getPgId() {
		return this.pgId;
	}

	public void setPgId(Integer pgId) {
		this.pgId = pgId;
	}

	public DcpRadio getDcpRadio() {
		return this.dcpRadio;
	}

	public void setDcpRadio(DcpRadio dcpRadio) {
		this.dcpRadio = dcpRadio;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Float getFramerate() {
		return this.framerate;
	}

	public void setFramerate(Float framerate) {
		this.framerate = framerate;
	}

	public Integer getFormat() {
		return this.format;
	}

	public void setFormat(Integer format) {
		this.format = format;
	}

	public String getPgname() {
		return this.pgname;
	}

	public void setPgname(String pgname) {
		this.pgname = pgname;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

}
