package com.divx.service.domain.model;

// Generated 2015-2-5 15:50:16 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpTranscode generated by hbm2java
 */
public class DcpTranscode implements java.io.Serializable {

	private Integer transcodeId;
	private int assetId;
	private String asseturl;
	private Date datecreated;
	private Date datemodified;
	private int status;
	private Integer trycount;
	private String log;
	private Integer errorstatus;
	private Integer jobtype;
	private String jobname;

	public DcpTranscode() {
	}

	public DcpTranscode(int assetId, String asseturl, Date datecreated,
			Date datemodified, int status) {
		this.assetId = assetId;
		this.asseturl = asseturl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.status = status;
	}

	public DcpTranscode(int assetId, String asseturl, Date datecreated,
			Date datemodified, int status, Integer trycount, String log,
			Integer errorstatus, Integer jobtype, String jobname) {
		this.assetId = assetId;
		this.asseturl = asseturl;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.status = status;
		this.trycount = trycount;
		this.log = log;
		this.errorstatus = errorstatus;
		this.jobtype = jobtype;
		this.jobname = jobname;
	}

	public Integer getTranscodeId() {
		return this.transcodeId;
	}

	public void setTranscodeId(Integer transcodeId) {
		this.transcodeId = transcodeId;
	}

	public int getAssetId() {
		return this.assetId;
	}

	public void setAssetId(int assetId) {
		this.assetId = assetId;
	}

	public String getAsseturl() {
		return this.asseturl;
	}

	public void setAsseturl(String asseturl) {
		this.asseturl = asseturl;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getTrycount() {
		return this.trycount;
	}

	public void setTrycount(Integer trycount) {
		this.trycount = trycount;
	}

	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public Integer getErrorstatus() {
		return this.errorstatus;
	}

	public void setErrorstatus(Integer errorstatus) {
		this.errorstatus = errorstatus;
	}

	public Integer getJobtype() {
		return this.jobtype;
	}

	public void setJobtype(Integer jobtype) {
		this.jobtype = jobtype;
	}

	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

}
