package com.divx.service.domain.model;

// Generated 2015-2-5 15:50:16 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpTranscodeOutput generated by hbm2java
 */
public class DcpTranscodeOutput implements java.io.Serializable {

	private Integer transcodeOutputId;
	private int transcodeId;
	private String fileurl;
	private int filetype;
	private Date datecreated;
	private Date datemodified;
	private int status;

	public DcpTranscodeOutput() {
	}

	public DcpTranscodeOutput(int transcodeId, String fileurl, int filetype,
			Date datecreated, Date datemodified, int status) {
		this.transcodeId = transcodeId;
		this.fileurl = fileurl;
		this.filetype = filetype;
		this.datecreated = datecreated;
		this.datemodified = datemodified;
		this.status = status;
	}

	public Integer getTranscodeOutputId() {
		return this.transcodeOutputId;
	}

	public void setTranscodeOutputId(Integer transcodeOutputId) {
		this.transcodeOutputId = transcodeOutputId;
	}

	public int getTranscodeId() {
		return this.transcodeId;
	}

	public void setTranscodeId(int transcodeId) {
		this.transcodeId = transcodeId;
	}

	public String getFileurl() {
		return this.fileurl;
	}

	public void setFileurl(String fileurl) {
		this.fileurl = fileurl;
	}

	public int getFiletype() {
		return this.filetype;
	}

	public void setFiletype(int filetype) {
		this.filetype = filetype;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
