package com.divx.service.domain.model;

// Generated 2015-2-5 15:50:16 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DcpTranscodeJob generated by hbm2java
 */
public class DcpTranscodeJob implements java.io.Serializable {

	private Integer jobId;
	private int transcodeId;
	private Date datecreated;
	private Date datemodifed;
	private String jobname;
	private int status;
	private Integer format;

	public DcpTranscodeJob() {
	}

	public DcpTranscodeJob(int transcodeId, Date datecreated, Date datemodifed,
			int status) {
		this.transcodeId = transcodeId;
		this.datecreated = datecreated;
		this.datemodifed = datemodifed;
		this.status = status;
	}

	public DcpTranscodeJob(int transcodeId, Date datecreated, Date datemodifed,
			String jobname, int status, Integer format) {
		this.transcodeId = transcodeId;
		this.datecreated = datecreated;
		this.datemodifed = datemodifed;
		this.jobname = jobname;
		this.status = status;
		this.format = format;
	}

	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	public int getTranscodeId() {
		return this.transcodeId;
	}

	public void setTranscodeId(int transcodeId) {
		this.transcodeId = transcodeId;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDatemodifed() {
		return this.datemodifed;
	}

	public void setDatemodifed(Date datemodifed) {
		this.datemodifed = datemodifed;
	}

	public String getJobname() {
		return this.jobname;
	}

	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Integer getFormat() {
		return this.format;
	}

	public void setFormat(Integer format) {
		this.format = format;
	}

}
