<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="edit" targetNamespace="http://service.divx.com/" xmlns:ns1="http://service.divx.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:portType name="edit">
  </wsdl:portType>
</wsdl:definitions>
