
package com.divx.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Fri Oct 24 14:54:42 CST 2014
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "MyMessagesResponse", namespace = "http://service.divx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MyMessagesResponse", namespace = "http://service.divx.com/")

public class MyMessagesResponse {

    @XmlElement(name = "return")
    private com.divx.service.model.MyMessagesResponse _return;

    public com.divx.service.model.MyMessagesResponse getReturn() {
        return this._return;
    }

    public void setReturn(com.divx.service.model.MyMessagesResponse new_return)  {
        this._return = new_return;
    }

}

