
package com.divx.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Thu Sep 11 16:22:07 CST 2014
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "Say", namespace = "http://service.divx.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Say", namespace = "http://service.divx.com/")

public class Say {


}

